sudo: false
dist: trusty

language: node_js
node_js:
  - "8"

cache:
  directories:
    - Frontend/node_modules

addons:
  chrome: stable

branches:
  only:
    - master

install:
  - cd $TRAVIS_BUILD_DIR
  - cd Frontend
  - npm install
  - npm install @angular/cli@7.3.8

script:
  - cd $TRAVIS_BUILD_DIR
  - cd Frontend
  - ng build --prod --aot
