sudo: false
dist: trusty

frontend:
  include:
  - language: node_js

node_js:
  - "8.15.1"

cache:
  directories:
    - Frontend/node_modules

addons:
  chrome: stable

install:
  - cd $TRAVIS_BUILD_DIR
  - cd Frontend
  - npm install
  - npm install @angular/cli@7.3.8

script:
  - cd $TRAVIS_BUILD_DIR
  - cd Frontend
  - ng build --prod --aot

after_success:
  - language: java
  jdk:
  - oraclejdk11

install:
  - cd $TRAVIS_BUILD_DIR
  - cd Backend
  - mvn dependency:resolve

script:
  - mvn package
