version: '3.4'

services:
  frontend:
    build:
      dockerfile: dev.dockerfile
    working_dir: /usr/src/frontend
    volumes:
      - ./Frontend/:/usr/src/frontend
      - /usr/src/frontend/node_modules
    ports:
     - '4200:4200'
     - '49153:49153'
     - '9876:9876'
     - '49152:49152'
    expose:
     - '4200'
     - '49153'
     - '9876'
     - '49152'
    command: ng serve --host 0.0.0.0 --poll 500

  backend:
    build:
      dockerfile: dev.dockerfile
    working_dir: /usr/src/backend
    volumes:
      - ./Backend/:/usr/src/backend
    ports:
      - '8080:8080'
      - '35729:35729'
    expose:
      - '8080'
      - '35729'
    command: mvn spring-boot:run