version: '3'

services:
  frontend:
    build: Frontend
    working_dir: /usr/src/frontend
    volumes:
      - ./Frontend/:/usr/src/frontend
      - /usr/src/frontend/node_modules
    ports:
     - '4200:4200'
     - '49153:49153'
     - '9876:9876'
     - '49152:49152'
    expose:
     - '4200'
     - '49153'
     - '9876'
     - '49152'
    command: ng serve --host 0.0.0.0 --poll 500
  
  database:
    image: mysql:5.7
    networks:
      backend:
        aliases:
          - mysql
    environment:
      - "MYSQL_DATABASE=trackthor"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"

  backend:
    build: Backend
    working_dir: /usr/src/backend
    volumes:
      - ./Backend/:/usr/src/backend
    networks:
      backend:
        aliases:
          - backend
    ports:
      - '8080:8080'
    expose:
      - '8080'
    command: mvn spring-boot:run

networks:
  backend: