version: '3.4'

services:
  frontend:
    build:
      context: Frontend
  
  database:
    image: mysql:5.7
    networks:
      backend:
        aliases:
          - mysql
    environment:
      - "MYSQL_DATABASE=trackthor"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"

  backend:
    build:
      context: Backend
    networks:
      backend:
        aliases:
          - backend

networks:
  backend: